### ISSUE TITLE
typo in documentation

### ISSUE THREAD

**Issue by WS2133** [it-blockchainglobal/acx#2]
It should be secret_key instead of two api_key in the initialise section in documentation

const ACX = require('acx');
var acx = new ACX({maret:"dashbtc", access_key:<access_key>, **access_key**:<secret_key>);
const ACX = require('acx');
var acx = new ACX({maret:"dashbtc", access_key:<access_key>, **access_key**:<secret_key>, tradeFee:0.001);

**Comment by yan-bgl** [comment]
Thanks for notice. The typo was corrected. Appreciate!
